### ISSUE TITLE
Demo maven install fail

### ISSUE THREAD

**Issue by JasonHuangHuster** [BroadleafCommerce/LegacyDemoSite#194] opened 2016-09-19 03:40 UTC
maven install end with this problem . try multiple times and i'm sure my network is fine .

[INFO] 
[INFO] ecommerce .......................................... SUCCESS [  0.242 s]
[INFO] core ............................................... FAILURE [01:20 min]
[INFO] admin .............................................. SKIPPED
[INFO] site ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2016-09-19T10:59:54+08:00
[INFO] Final Memory: 9M/184M

Failed to execute goal on project core: Could not resolve dependencies for project com.mycompany-community:core:jar:5.0: Failed to collect dependencies at org.broadleafcommerce:broadleaf-framework:jar:5.0.1-GA: Failed to read artifact descriptor for org.broadleafcommerce:broadleaf-framework:jar:5.0.1-GA: Could not transfer artifact org.broadleafcommerce:broadleaf-framework:pom:5.0.1-GA from/to public snapshots (http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/): connect timed out -> [Help 1]

i've searched the forums around , and there are many question like this but without solutions ... failed at the beginning of demo , it's really painful , so , can any one help me out .. :(

**Comment by Jerry77oz** [comment] 2016-09-30 15:44
Hi Jason, 

You can see in the `POM.xml` that 2 repositories are called out:

```
    <repositories>
        <repository>
            <id>public snapshots</id>
            <name>public snapshots</name>
            <url>http://nexus.broadleafcommerce.org/nexus/content/groups/community-snapshots/</url>
        </repository>
        <repository>
            <id>public releases</id>
            <name>public releases</name>
            <url>http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/</url>
        </repository>
    </repositories>
```

If you are just using `GA` versions you could remove the `community-snapshots` repository or move the `community-releases` to be first. The problem is that it is trying to get a `GA` release on **Snapshot** repository.

I'll close this issue for now since we encourage community users to use the forums for questions like this.

**Closed as completed by Jerry77oz** 2016-09-30 15:44 UTC
